values:
  defaultValues: |
    ingress:
      hostname: keycloak.local.gd
    customLivenessProbe:
      failureThreshold: 3
      httpGet:
        path: /auth
        port: http
        scheme: HTTP
      initialDelaySeconds: 600
      periodSeconds: 1
      successThreshold: 1
      timeoutSeconds: 5